CREATE SCHEMA IF NOT EXISTS datalogger;

CREATE TABLE datalogger."user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE datalogger.device (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE datalogger.user_device (
    user_id INTEGER NOT NULL REFERENCES datalogger."user"(id),
    device_id INTEGER NOT NULL REFERENCES datalogger.device(id),
    PRIMARY KEY (user_id, device_id)
);

CREATE TABLE datalogger.gps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL REFERENCES datalogger.device(id),
    time INTEGER,
    sentence VARCHAR(255) NOT NULL
);

CREATE TABLE datalogger.gyroacc (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL REFERENCES datalogger.device(id),
    time INTEGER,
    gyro_x INTEGER,
    gyro_y INTEGER,
    gyro_z INTEGER,
    acc_x INTEGER,
    acc_y INTEGER,
    acc_z INTEGER
);

CREATE TABLE datalogger.temphum (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL REFERENCES datalogger.device(id),
    time INTEGER,
    temperature INTEGER,
    humidity INTEGER
);
